import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import Hero from '../../components/Hero'
export default function Home() {
  return (
    <>
      <Head>
        <title>Cryptocurrency Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      < Header />

      <div className='bg-[url("/images/Background.png")]'>


      {/*Hero*/}
      < Hero />
      </div>

      {/*Footer*/}
      < Footer />
    
    </>
  )
}
